name: Update University Food Menu

on:
  workflow_dispatch: # اجرای دستی از تب Actions
  schedule:
    # At 04:00 UTC on Saturday (corresponds to Saturday morning in Iran)
    - cron: '0 4 * * 6'

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: List files for debugging
      - name: List files in the repository
        run: ls -R

      # Step 3: Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 4: Installs required Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Step 5: Runs the scraper script to download the menu files
      - name: Run scraper to update menu files
        env:
          UNIVERSITY_USERNAME: ${{ secrets.UNIVERSITY_USERNAME }}
          UNIVERSITY_PASSWORD: ${{ secrets.UNIVERSITY_PASSWORD }}
          run: |
              ls -R   
              python scraper.py

      # Step 6: Commits and pushes the updated menu files to your repository
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add layouts/*.html
          
          if ! git diff --staged --quiet; then
            git commit -m "chore(bot): Update weekly food menus"
            git push
          else
            echo "No changes to the menu files."
          fi
